<header>
  <nav class="navbar">
    <div class="navbar_nom"><h1>Mon Portfolio</h1></div>
    <ul class="navbar-nav">
      <li class="nav-item"><a href="#">Accueil</a></li>
      <li class="nav-item"><a href="#">Mes Projets</a></li>
      <li class="nav-item apropos-item">
        <a href="#apropos">À propos <i class="fa-solid fa-caret-down"></i></a>
        <ul class="submenu">
          <li class="nav-item"><a href="#">Moi Justin</a></li>
          <li class="nav-item"><a href="#">Cv</a></li>
          <li class="nav-item"><a href="#">Compétences</a></li>
        </ul>
      </li>
      <li class="nav-item"><a href="#">Connect</a></li>
    </ul>
  </nav>
</header>
